# Base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application code
COPY src/ /app

# Expose the application port
EXPOSE 5000

# Command to run the app
CMD ["python", "app.py"]
